config/routes.rb
KidsBank::Application.routes.draw do
  resources :cards
  resources :accounts
  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"

  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  
# Relations
has_many :posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Pagination
  paginates_per 100

  # Validations
  # :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  def self.paged(page_number)
    order(admin: :desc, email: :asc).page page_number
  end

  def self.search_and_order(search, page_number)
    if search
      where("email LIKE ?", "%#{search.downcase}%").order(
      admin: :desc, email: :asc
      ).page page_number
    else
      order(admin: :desc, email: :asc).page page_number
    end
  end

  def self.last_signups(count)
    order(created_at: :desc).limit(count).select("id","email","created_at")
  end

  def self.last_signins(count)
    order(last_sign_in_at:
    :desc).limit(count).select("id","email","last_sign_in_at")
  end

  def self.users_count
    where("admin = ? AND locked = ?",false,false).count
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  before_action :set_user, only: [
    :show,
    :edit,
    :update,
    :destroy
  ]


  def index
    @users = User.search_and_order(params[:search], params[:page])
  end

  def show
    redirect_to edit_admin_user_path(params[:id])
  end

  def edit
  end

  def update
    old_email = @user.email
    new_params = user_params.dup
    new_params[:email] = new_params[:email].strip

    @user.email = new_params[:email]
    @user.password = new_params[:password] if new_params[:password].strip.length > 0
    @user.password_confirmation = new_params[:password_confirmation] if new_params[:password_confirmation].strip.length > 0

    if current_user.id != @user.id
      @user.admin = new_params[:admin]=="0" ? false : true
      @user.locked = new_params[:locked]=="0" ? false : true
    end

    if @user.valid?
      @user.skip_reconfirmation!
      @user.save
      redirect_to admin_users_path, notice: "#{@user.email} updated."
    else
      flash[:alert] = "#{old_email} couldn't be updated."
      render :edit
    end
  end


  private

  def set_user
    @user = User.find(params[:id])
  rescue
    flash[:alert] = "The user with an id of #{params[:id]} doesn't exist."
    redirect_to admin_users_path
  end

  def user_params
    params.require(:user).permit(
    :email,
    :password,
    :password_confirmation,
    :admin,
    :locked
    )
  end

end

app/views/admin/users/edit.html.erb
<% title("Edit User Id: #{@user.id}") %>
<div class="row">
  <div class="col-sm-6">
    <h1>
      Edit User <small><%= "#{@user.email} - id: #{@user.id}" %></small>
    </h1>
    <p><%= link_to "Back to Users", admin_users_path %></p>

    <%= form_for [:admin, @user], :html => { :role => "form" } do |f| %>

    <div class="form-group">
      <%= f.label :email %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>
    </div>

    <% unless current_user.id == @user.id %>
    <div class="form-group">
      <div class="row">
        <div class="col-sm-6">
          <%= f.check_box :locked %> <%= f.label :locked, "Is Locked?" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-sm-6">
          <%= f.check_box :admin %> <%= f.label :admin, "Is Admin?" %>
        </div>
      </div>
    </div>
    <% end %>

    <div class="row">
      <div class="col-sm-6">
        <%= f.submit "Update User", class: "btn btn-danger" %>
      </div>
    </div>

    <% end %>

  </div>
</div>

app/views/admin/users/index.html.erb
<% title("Users Admin") %>
<h1>Users <small>Admin</small></h1>
<p><%= link_to "Back to Admin", admin_root_path %></p>

<div class="text-center">
  <p><%= page_entries_info @users %></p>
  <%= paginate @users %>
</div>

<%= form_tag admin_users_path, method: 'get', html: {role: "form"} do %>
<p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>
  <%= link_to "All", admin_users_path, {class: "btn btn-sm btn-link"} %>
</p>
<% end %>

<table class="table table-striped">
  <tr>
    <th>User ID</th>
    <th>Email</th>
    <th>Admin</th>
    <th>Locked</th>
    <th>Sign In Count</th>
    <th>Created At</th>
    <th>Last Sign In</th>
    <th>Last Sign In IP</th>
  </tr>

  <% @users.each do |user| %>

  <tr>
    <td><%= user.id %></td>
    <td><%= link_to user.email, admin_user_path(user) %></td>
    <td><%= user.admin? ? "<b>yes</b>".html_safe : "no" %></td>
    <td><%= user.locked? ? "<b>yes</b>".html_safe : "no" %></td>
    <td><%= user.sign_in_count %></td>
    <td><%= time_ago_in_words(user.created_at) %></td>
    <% unless user.last_sign_in_at.nil? %>
    <td><%= time_ago_in_words(user.last_sign_in_at)%> ago</td>
    <% else %>
    <td>never</td>
    <% end %>
    <td><%= user.last_sign_in_ip %></td>
  </tr>

  <% end %>

</table>

<div class="text-center">
  <p><%= page_entries_info @users %></p>
  <%= paginate @users %>
</div>